#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INFRA_DIR="${ROOT_DIR}/infra"
REPO_NAME="$(basename "${ROOT_DIR}")"
RUN_ID_DEFAULT="$(date +%Y%m%d%H%M%S)-$$"
RUN_ID_RAW="${AWS_INTEGRATION_RUN_ID:-${RUN_ID_DEFAULT}}"
RUN_ID="$(printf '%s' "${RUN_ID_RAW}" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9-' '-')"
WORKDIR="${AWS_INTEGRATION_WORKDIR:-}"
KEEP_WORKDIR="${AWS_INTEGRATION_KEEP_WORKDIR:-0}"
MODE="${1:-plan}"
WORKDIR_CREATED=0
INTEGRATION_PREFIX=""
SERVICE_NAME=""
ECR_REPOSITORY_NAME=""
IMAGE_TAG=""
STATE_KEY=""
TFVARS_PATH=""
BACKEND_CONFIG_PATH=""
METADATA_PATH=""

usage() {
  cat <<'EOF'
Usage:
  ./scripts/run-aws-integration.sh [plan|foundation-apply]

This is the Phase 2 AWS integration runner skeleton.
Current behavior:
  - creates an isolated temp workdir
  - derives unique naming and state paths for an integration run
  - materializes isolated backend, tfvars, and metadata files
  - prints the intended command sequence and current TODO boundaries
  - optionally performs the first foundation apply

Environment overrides:
  AWS_INTEGRATION_RUN_ID       Override the generated run id
  AWS_INTEGRATION_WORKDIR      Reuse a specific working directory
  AWS_INTEGRATION_KEEP_WORKDIR Keep the workdir after exit when set to 1
  AWS_INTEGRATION_AUTO_APPROVE Set to 0 to omit -auto-approve on apply
EOF
}

cleanup() {
  if [ "${WORKDIR_CREATED}" != "1" ]; then
    if [ -n "${WORKDIR}" ]; then
      echo "Leaving user-supplied integration workdir in place: ${WORKDIR}"
    fi
    return
  fi

  if [ "${KEEP_WORKDIR}" = "1" ]; then
    echo "Keeping integration workdir: ${WORKDIR}"
    return
  fi

  if [ -n "${WORKDIR}" ] && [ -d "${WORKDIR}" ]; then
    rm -rf "${WORKDIR}"
  fi
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Required command not found: $1" >&2
    exit 1
  fi
}

validate_optional_env() {
  local env_name="$1"
  local env_value="$2"
  local env_pattern="$3"

  if [ -n "${env_value}" ] && ! printf '%s' "${env_value}" | grep -Eq "${env_pattern}"; then
    echo "Invalid value for ${env_name}: ${env_value}" >&2
    exit 1
  fi
}

require_materialized_value() {
  local field_name="$1"
  local field_value="$2"

  if [ -z "${field_value}" ] || printf '%s' "${field_value}" | grep -q '^__SET_'; then
    echo "Missing required integration input: ${field_name}" >&2
    exit 1
  fi
}

slugify() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9-' '-'
}

trim_name() {
  printf '%.40s' "$1"
}

prepare_workdir() {
  if [ -n "${WORKDIR}" ]; then
    mkdir -p "${WORKDIR}"
  else
    WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/${REPO_NAME}-${RUN_ID}-XXXXXX")"
    WORKDIR_CREATED=1
  fi
}

materialize_tfvars() {
  local aws_region_placeholder
  local github_owner_placeholder
  local tf_state_bucket_placeholder

  INTEGRATION_PREFIX="$(slugify "${REPO_NAME}-${RUN_ID}")"
  SERVICE_NAME="$(trim_name "${INTEGRATION_PREFIX}")"
  ECR_REPOSITORY_NAME="${SERVICE_NAME}"
  IMAGE_TAG="integration-${RUN_ID}"
  STATE_KEY="${REPO_NAME}/integration/${RUN_ID}.tfstate"
  TFVARS_PATH="${WORKDIR}/integration.tfvars"
  BACKEND_CONFIG_PATH="${WORKDIR}/backend.hcl"
  METADATA_PATH="${WORKDIR}/integration-metadata.json"
  validate_optional_env "AWS_REGION" "${AWS_REGION:-}" '^[a-z]{2}-[a-z0-9-]+-[0-9]+$'
  validate_optional_env "GITHUB_OWNER" "${GITHUB_OWNER:-}" '^[A-Za-z0-9_.-]+$'
  validate_optional_env "TF_STATE_BUCKET" "${TF_STATE_BUCKET:-}" '^[A-Za-z0-9.-]+$'
  aws_region_placeholder="${AWS_REGION:-__SET_AWS_REGION__}"
  github_owner_placeholder="${GITHUB_OWNER:-__SET_GITHUB_OWNER__}"
  tf_state_bucket_placeholder="${TF_STATE_BUCKET:-__SET_TF_STATE_BUCKET__}"

  cat > "${TFVARS_PATH}" <<EOF
# Generated by scripts/run-aws-integration.sh
# This file is intentionally isolated from infra/prod.tfvars.

aws_region          = "${aws_region_placeholder}"
service_name        = "${SERVICE_NAME}"
apprunner_image_tag = "${IMAGE_TAG}"
github_owner        = "${github_owner_placeholder}"
github_repo         = "${REPO_NAME}"
github_branch       = "main"
EOF

  cat > "${BACKEND_CONFIG_PATH}" <<EOF
# Generated by scripts/run-aws-integration.sh
bucket       = "${tf_state_bucket_placeholder}"
key          = "${STATE_KEY}"
region       = "${aws_region_placeholder}"
use_lockfile = true
EOF

  jq -n \
    --arg run_id "${RUN_ID}" \
    --arg integration_prefix "${INTEGRATION_PREFIX}" \
    --arg service_name "${SERVICE_NAME}" \
    --arg ecr_repository_name "${ECR_REPOSITORY_NAME}" \
    --arg image_tag "${IMAGE_TAG}" \
    --arg state_key "${STATE_KEY}" \
    --arg tfvars_path "${TFVARS_PATH}" \
    --arg backend_config_path "${BACKEND_CONFIG_PATH}" \
    '{
      run_id: $run_id,
      integration_prefix: $integration_prefix,
      service_name: $service_name,
      ecr_repository_name: $ecr_repository_name,
      image_tag: $image_tag,
      state_key: $state_key,
      tfvars_path: $tfvars_path,
      backend_config_path: $backend_config_path
    }' > "${METADATA_PATH}"

  cat <<EOF
Run ID: ${RUN_ID}
Workdir: ${WORKDIR}
Integration prefix: ${INTEGRATION_PREFIX}
Integration tfvars: ${TFVARS_PATH}
Integration backend config: ${BACKEND_CONFIG_PATH}
Integration metadata: ${METADATA_PATH}
Suggested backend key: ${STATE_KEY}
Derived service name: ${SERVICE_NAME}
Derived ECR repository name: ${ECR_REPOSITORY_NAME}
Expected bootstrap image tag: ${IMAGE_TAG}
EOF
}

print_plan() {
  cat <<EOF

Planned AWS integration sequence
1. Initialize OpenTofu with an isolated backend key:
   cd "${INFRA_DIR}"
   tofu init -backend-config="${BACKEND_CONFIG_PATH}"

2. Run the first foundation apply with isolated vars:
   tofu apply -var-file="${TFVARS_PATH}"

3. Publish the bootstrap image to ECR repository ${ECR_REPOSITORY_NAME} using tag ${IMAGE_TAG}.
   TODO: wire this to a known fixture image and explicit Docker/ECR auth checks.

4. Run the second apply so Terraform can create the App Runner service:
   tofu apply -var-file="${TFVARS_PATH}"

5. Fetch the App Runner service URL and verify the public fixture response.
   TODO: decide whether the runner should use tofu output, AWS CLI, or both.

6. Destroy the isolated integration stack and remove temp artifacts:
   tofu destroy -var-file="${TFVARS_PATH}"
   TODO: add cleanup safeguards for partial failures.

Current boundary:
- This runner now supports the isolated foundation apply.
- It still does not publish the bootstrap image, create the runtime service on a
  second apply, verify the public URL, or destroy integration infrastructure.
EOF
}

run_foundation_apply() {
  local auto_approve="${AWS_INTEGRATION_AUTO_APPROVE:-1}"

  require_materialized_value "AWS_REGION" "${AWS_REGION:-}"
  require_materialized_value "TF_STATE_BUCKET" "${TF_STATE_BUCKET:-}"
  require_materialized_value "GITHUB_OWNER" "${GITHUB_OWNER:-}"

  echo
  echo "Running isolated foundation apply"
  echo "Infra dir: ${INFRA_DIR}"
  echo "Backend config: ${BACKEND_CONFIG_PATH}"
  echo "Vars file: ${TFVARS_PATH}"

  (
    cd "${INFRA_DIR}"
    tofu init -backend-config="${BACKEND_CONFIG_PATH}"

    if [ "${auto_approve}" = "0" ]; then
      tofu apply -var-file="${TFVARS_PATH}"
    else
      tofu apply -auto-approve -var-file="${TFVARS_PATH}"
    fi
  )
}

main() {
  if [ "${MODE}" = "--help" ] || [ "${MODE}" = "-h" ]; then
    usage
    exit 0
  fi

  if [ "${MODE}" != "plan" ] && [ "${MODE}" != "foundation-apply" ]; then
    echo "Unsupported mode: ${MODE}" >&2
    usage >&2
    exit 1
  fi

  require_command tofu
  require_command git
  require_command jq
  require_command mktemp

  trap cleanup EXIT

  prepare_workdir
  materialize_tfvars

  if [ "${MODE}" = "plan" ]; then
    print_plan
    return
  fi

  run_foundation_apply
}

main "$@"
