#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INFRA_DIR="${ROOT_DIR}/infra"
REPO_NAME="$(basename "${ROOT_DIR}")"
RUN_ID_DEFAULT="$(date +%Y%m%d%H%M%S)-$$"
RUN_ID="${AWS_INTEGRATION_RUN_ID:-${RUN_ID_DEFAULT}}"
WORKDIR="${AWS_INTEGRATION_WORKDIR:-}"
KEEP_WORKDIR="${AWS_INTEGRATION_KEEP_WORKDIR:-0}"
MODE="${1:-plan}"

usage() {
  cat <<'EOF'
Usage:
  ./scripts/run-aws-integration.sh [plan]

This is the Phase 2 AWS integration runner skeleton.
Current behavior:
  - creates an isolated temp workdir
  - derives unique naming and state paths for an integration run
  - materializes an isolated tfvars file from the template
  - prints the intended command sequence and current TODO boundaries

Environment overrides:
  AWS_INTEGRATION_RUN_ID       Override the generated run id
  AWS_INTEGRATION_WORKDIR      Reuse a specific working directory
  AWS_INTEGRATION_KEEP_WORKDIR Keep the workdir after exit when set to 1
EOF
}

cleanup() {
  if [ "${KEEP_WORKDIR}" = "1" ]; then
    echo "Keeping integration workdir: ${WORKDIR}"
    return
  fi

  if [ -n "${WORKDIR}" ] && [ -d "${WORKDIR}" ]; then
    rm -rf "${WORKDIR}"
  fi
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Required command not found: $1" >&2
    exit 1
  fi
}

slugify() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9-' '-'
}

trim_name() {
  printf '%.40s' "$1"
}

prepare_workdir() {
  if [ -n "${WORKDIR}" ]; then
    mkdir -p "${WORKDIR}"
  else
    WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/${REPO_NAME}-${RUN_ID}-XXXXXX")"
  fi
}

materialize_tfvars() {
  local tfvars_path="${WORKDIR}/integration.tfvars"
  local base_service_name
  local service_name
  local image_tag
  local state_key

  base_service_name="$(slugify "${REPO_NAME}-${RUN_ID}")"
  service_name="$(trim_name "${base_service_name}")"
  image_tag="integration-${RUN_ID}"
  state_key="${REPO_NAME}/integration/${RUN_ID}.tfstate"

  cat > "${tfvars_path}" <<EOF
# Generated by scripts/run-aws-integration.sh
# This file is intentionally isolated from infra/prod.tfvars.

service_name        = "${service_name}"
apprunner_image_tag = "${image_tag}"
github_repo         = "${REPO_NAME}"
github_branch       = "main"
EOF

  cat <<EOF
Run ID: ${RUN_ID}
Workdir: ${WORKDIR}
Integration tfvars: ${tfvars_path}
Suggested backend key: ${state_key}
Derived service name: ${service_name}
Expected bootstrap image tag: ${image_tag}
EOF
}

print_plan() {
  local tfvars_path="${WORKDIR}/integration.tfvars"

  cat <<EOF

Planned AWS integration sequence
1. Initialize OpenTofu with an isolated backend key:
   cd "${INFRA_DIR}"
   tofu init \\
     -backend-config="bucket=\$TF_STATE_BUCKET" \\
     -backend-config="key=${REPO_NAME}/integration/${RUN_ID}.tfstate" \\
     -backend-config="region=\$AWS_REGION" \\
     -backend-config="use_lockfile=true"

2. Run the first foundation apply with isolated vars:
   tofu apply -var-file="${tfvars_path}"

3. Publish the bootstrap image to ECR using tag integration-${RUN_ID}.
   TODO: wire this to a known fixture image and explicit Docker/ECR auth checks.

4. Run the second apply so Terraform can create the App Runner service:
   tofu apply -var-file="${tfvars_path}"

5. Fetch the App Runner service URL and verify the public fixture response.
   TODO: decide whether the runner should use tofu output, AWS CLI, or both.

6. Destroy the isolated integration stack and remove temp artifacts:
   tofu destroy -var-file="${tfvars_path}"
   TODO: add cleanup safeguards for partial failures.

Current boundary:
- This skeleton prepares the isolated workspace and naming strategy only.
- It does not call AWS, Docker, or tofu apply yet.
EOF
}

main() {
  if [ "${MODE}" = "--help" ] || [ "${MODE}" = "-h" ]; then
    usage
    exit 0
  fi

  if [ "${MODE}" != "plan" ]; then
    echo "Unsupported mode: ${MODE}" >&2
    usage >&2
    exit 1
  fi

  require_command tofu
  require_command git
  require_command mktemp

  trap cleanup EXIT

  prepare_workdir
  materialize_tfvars
  print_plan
}

main "$@"
