#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INFRA_DIR="${ROOT_DIR}/infra"
REPO_NAME="$(basename "${ROOT_DIR}")"
RUN_ID_DEFAULT="$(date +%Y%m%d%H%M%S)-$$"
RUN_ID_RAW="${AWS_INTEGRATION_RUN_ID:-${RUN_ID_DEFAULT}}"
RUN_ID="$(printf '%s' "${RUN_ID_RAW}" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9-' '-')"
WORKDIR="${AWS_INTEGRATION_WORKDIR:-}"
KEEP_WORKDIR="${AWS_INTEGRATION_KEEP_WORKDIR:-0}"
MODE="${1:-plan}"
WORKDIR_CREATED=0
INTEGRATION_PREFIX=""
SERVICE_NAME=""
ECR_REPOSITORY_NAME=""
IMAGE_TAG=""
STATE_KEY=""
TFVARS_PATH=""
BACKEND_CONFIG_PATH=""
METADATA_PATH=""

usage() {
  cat <<'EOF'
Usage:
  ./scripts/run-aws-integration.sh [plan]

This is the Phase 2 AWS integration runner skeleton.
Current behavior:
  - creates an isolated temp workdir
  - derives unique naming and state paths for an integration run
  - materializes isolated backend, tfvars, and metadata files
  - prints the intended command sequence and current TODO boundaries

Environment overrides:
  AWS_INTEGRATION_RUN_ID       Override the generated run id
  AWS_INTEGRATION_WORKDIR      Reuse a specific working directory
  AWS_INTEGRATION_KEEP_WORKDIR Keep the workdir after exit when set to 1
EOF
}

cleanup() {
  if [ "${WORKDIR_CREATED}" != "1" ]; then
    if [ -n "${WORKDIR}" ]; then
      echo "Leaving user-supplied integration workdir in place: ${WORKDIR}"
    fi
    return
  fi

  if [ "${KEEP_WORKDIR}" = "1" ]; then
    echo "Keeping integration workdir: ${WORKDIR}"
    return
  fi

  if [ -n "${WORKDIR}" ] && [ -d "${WORKDIR}" ]; then
    rm -rf "${WORKDIR}"
  fi
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Required command not found: $1" >&2
    exit 1
  fi
}

slugify() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9-' '-'
}

trim_name() {
  printf '%.40s' "$1"
}

prepare_workdir() {
  if [ -n "${WORKDIR}" ]; then
    mkdir -p "${WORKDIR}"
  else
    WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/${REPO_NAME}-${RUN_ID}-XXXXXX")"
    WORKDIR_CREATED=1
  fi
}

materialize_tfvars() {
  local aws_region_placeholder
  local github_owner_placeholder
  local tf_state_bucket_placeholder

  INTEGRATION_PREFIX="$(slugify "${REPO_NAME}-${RUN_ID}")"
  SERVICE_NAME="$(trim_name "${INTEGRATION_PREFIX}")"
  ECR_REPOSITORY_NAME="${SERVICE_NAME}"
  IMAGE_TAG="integration-${RUN_ID}"
  STATE_KEY="${REPO_NAME}/integration/${RUN_ID}.tfstate"
  TFVARS_PATH="${WORKDIR}/integration.tfvars"
  BACKEND_CONFIG_PATH="${WORKDIR}/backend.hcl"
  METADATA_PATH="${WORKDIR}/integration-metadata.json"
  aws_region_placeholder="${AWS_REGION:-__SET_AWS_REGION__}"
  github_owner_placeholder="${GITHUB_OWNER:-__SET_GITHUB_OWNER__}"
  tf_state_bucket_placeholder="${TF_STATE_BUCKET:-__SET_TF_STATE_BUCKET__}"

  cat > "${TFVARS_PATH}" <<EOF
# Generated by scripts/run-aws-integration.sh
# This file is intentionally isolated from infra/prod.tfvars.

aws_region          = "${aws_region_placeholder}"
service_name        = "${SERVICE_NAME}"
apprunner_image_tag = "${IMAGE_TAG}"
github_owner        = "${github_owner_placeholder}"
github_repo         = "${REPO_NAME}"
github_branch       = "main"
EOF

  cat > "${BACKEND_CONFIG_PATH}" <<EOF
# Generated by scripts/run-aws-integration.sh
bucket       = "${tf_state_bucket_placeholder}"
key          = "${STATE_KEY}"
region       = "${aws_region_placeholder}"
use_lockfile = true
EOF

  cat > "${METADATA_PATH}" <<EOF
{
  "run_id": "${RUN_ID}",
  "integration_prefix": "${INTEGRATION_PREFIX}",
  "service_name": "${SERVICE_NAME}",
  "ecr_repository_name": "${ECR_REPOSITORY_NAME}",
  "image_tag": "${IMAGE_TAG}",
  "state_key": "${STATE_KEY}",
  "tfvars_path": "${TFVARS_PATH}",
  "backend_config_path": "${BACKEND_CONFIG_PATH}"
}
EOF

  cat <<EOF
Run ID: ${RUN_ID}
Workdir: ${WORKDIR}
Integration prefix: ${INTEGRATION_PREFIX}
Integration tfvars: ${TFVARS_PATH}
Integration backend config: ${BACKEND_CONFIG_PATH}
Integration metadata: ${METADATA_PATH}
Suggested backend key: ${STATE_KEY}
Derived service name: ${SERVICE_NAME}
Derived ECR repository name: ${ECR_REPOSITORY_NAME}
Expected bootstrap image tag: ${IMAGE_TAG}
EOF
}

print_plan() {
  cat <<EOF

Planned AWS integration sequence
1. Initialize OpenTofu with an isolated backend key:
   cd "${INFRA_DIR}"
   tofu init -backend-config="${BACKEND_CONFIG_PATH}"

2. Run the first foundation apply with isolated vars:
   tofu apply -var-file="${TFVARS_PATH}"

3. Publish the bootstrap image to ECR repository ${ECR_REPOSITORY_NAME} using tag ${IMAGE_TAG}.
   TODO: wire this to a known fixture image and explicit Docker/ECR auth checks.

4. Run the second apply so Terraform can create the App Runner service:
   tofu apply -var-file="${TFVARS_PATH}"

5. Fetch the App Runner service URL and verify the public fixture response.
   TODO: decide whether the runner should use tofu output, AWS CLI, or both.

6. Destroy the isolated integration stack and remove temp artifacts:
   tofu destroy -var-file="${TFVARS_PATH}"
   TODO: add cleanup safeguards for partial failures.

Current boundary:
- This skeleton prepares the isolated workspace and materialized integration config only.
- It does not call AWS, Docker, or tofu apply yet.
EOF
}

main() {
  if [ "${MODE}" = "--help" ] || [ "${MODE}" = "-h" ]; then
    usage
    exit 0
  fi

  if [ "${MODE}" != "plan" ]; then
    echo "Unsupported mode: ${MODE}" >&2
    usage >&2
    exit 1
  fi

  require_command tofu
  require_command git
  require_command mktemp

  trap cleanup EXIT

  prepare_workdir
  materialize_tfvars
  print_plan
}

main "$@"
